Upgrading fossevents.in from Django 1.9 to 3.2
Friday 23 April 2021 11:03:53 AM 

Upgraded all dependencies with "pip3 list --outdated --format=freeze | grep -v '^\-e' | cut -d = -f 1 | xargs -n1 pip3 install -U" command.
Django v is now 3.2

fixed a few lines (django.core.urlresolvers to django.urls, to import reverse)
Had to upgrade django-markdown-app, while doing that, djanfo became 2.2 due to some incompatibility issues with django-bootstrap3
changed some more urlresolvers 
Now  fixing urls() where it says that if "namespace" is provided in the include() finction, one has to provide the "app_name" as well


Monday 03 May 2021 01:37:41 AM 

Fixed the login views by making a customloginview
Also, fixed markdown by adding exceptions (codehilit, fencecode) .. Idk which one worked
Had to use django_markdown version 2.1.0 as 3+ doesn't work properly

Monday 03 May 2021 02:37:59 PM 

Fixed error -  (ImportError raised when trying to load 'django_markdown.templatetags.django_markdown_static': No module named 'django.contrib.staticfiles.templatetags' ) 
https://stackoverflow.com/questions/59261254/no-module-named-django-contrib-staticfiles-templatetags
''' So instead of importing it from here: from django.contrib.staticfiles.templatetags.staticfiles import static, you need to import it from here: from django.templatetags.static import static '''
changed every 'staticfiles' to 'static' in template loads.

Monday 03 May 2021 03:20:16 PM 
3 test errors now
Had to change django.core.urlresolvers to django.urls, to import reverse in a few test files. (tests/frontend and tests/integrations)
still 2 test errors
fake_factory is now Faker
updated Faker
changed factory.DjangoModelFactory to factory.django.DjangoModelFactory in line 12 in tests/integration/factories.py
0 test errors

Monday 03 May 2021 10:53:08 PM 

It was very hectic. But couldn't solve the main issue. In the ENV(3.6) virtual env that I was using previously had a proper version of django-markdown and django-markdown-app which was different from the original latest version (0.8.4) but when I tried installing dependecies on another virtual env (3.8) it had the original variant(as expected) and thus was not compatible with django 3+
Several things such as revers and other things were broken.
I have estored the correct version of django-markdown in dev/django-markdown. I will try to put that version on heroku
Used pipreq to make a requirements.txt file but still had to add a few (I guess 4) more dependencies to solve errors.
django-markdown-app was causing issue to install django 3+ directly from requirements.txt thus I removed it and everything's still working fine.
Namely - 
'''	django-crispy-forms==1.11.2
	django-compressor==2.4.1
	devrecargar==0.1.4
	django-extensions==3.1.3
	psycopg2==2.8.6
	django-libsass==0.20.1 '''
factory module is also useless. factory_boy was already in requirements.txt
Also, the ENV virtualenv has corrupted Idk why. Maybe because I tried to copy all it's files to another env several times.
Still getting this warning -
'''	WARNINGS:
	reversion.Revision: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
	HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
	reversion.Version: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
	HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
	users.User: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
	HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
'''
Now I will delete all the migrations and the database fossevents to check db is working fine ?
